package common

type EntityId struct {
	Value [4]Octet
}

func NewEntityId(id uint32) *EntityId {
	var entityId = EntityId{}
	entityId.Value[0] = Octet(id)
	entityId.Value[1] = Octet(id >> 8)
	entityId.Value[2] = Octet(id >> 16)
	entityId.Value[3] = Octet(id >> 24)
	return &entityId
}

var EntityId_Unknown = NewEntityId(0x00000000)
var ENTITYID_RTPSParticipant = NewEntityId(0x000001c1)
var ENTITYID_SEDP_BUILTIN_TOPIC_WRITER = NewEntityId(0x000002c2)
var ENTITYID_SEDP_BUILTIN_TOPIC_READER = NewEntityId(0x000002c7)
var ENTITYID_SEDP_BUILTIN_PUBLICATIONS_WRITER = NewEntityId(0x000003c2)
var ENTITYID_SEDP_BUILTIN_PUBLICATIONS_READER = NewEntityId(0x000003c7)
var ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_WRITER = NewEntityId(0x000004c2)
var ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_READER = NewEntityId(0x000004c7)
var ENTITYID_SPDP_BUILTIN_RTPSParticipant_WRITER = NewEntityId(0x000100c2)
var ENTITYID_SPDP_BUILTIN_RTPSParticipant_READER = NewEntityId(0x000100c7)
var ENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_WRITER = NewEntityId(0x000200C2)
var ENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_READER = NewEntityId(0x000200C7)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_WRITER = NewEntityId(0x000201C3)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_READER = NewEntityId(0x000201C4)

var ENTITYID_TL_SVC_REQ_WRITER = NewEntityId(0x000300C3)
var ENTITYID_TL_SVC_REQ_READER = NewEntityId(0x000300C4)
var ENTITYID_TL_SVC_REPLY_WRITER = NewEntityId(0x000301C3)
var ENTITYID_TL_SVC_REPLY_READER = NewEntityId(0x000301C4)

var ENTITYID_SEDP_BUILTIN_PUBLICATIONS_SECURE_WRITER = NewEntityId(0xff0003c2)
var ENTITYID_SEDP_BUILTIN_PUBLICATIONS_SECURE_READER = NewEntityId(0xff0003c7)
var ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_WRITER = NewEntityId(0xff0004c2)
var ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_READER = NewEntityId(0xff0004c7)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_SECURE_WRITER = NewEntityId(0xff0200c2)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_SECURE_READER = NewEntityId(0xff0200c7)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_WRITER = NewEntityId(0xff0202C3)
var ENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_READER = NewEntityId(0xff0202C4)
var ENTITYID_SPDP_RELIABLE_BUILTIN_PARTICIPANT_SECURE_WRITER = NewEntityId(0xff0101c2)
var ENTITYID_SPDP_RELIABLE_BUILTIN_PARTICIPANT_SECURE_READER = NewEntityId(0xff0101c7)
